# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: jhipster-exam.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url:  mysql://b32bbc5d41ed5c:2bf7c052@us-cdbr-iron-east-02.cleardb.net/heroku_6e5c45211a0a2e4?reconnect=true
        username: b32bbc5d41ed5c
        password: 2bf7c052
        hikari:
            maximumPoolSize: 8
